# Generated by Django 5.1.5 on 2025-02-02 09:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("orders", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="equipment",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="equipment",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="equipmentsubcategory",
            name="category",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="orders.equipmentcategory",
            ),
        ),
        migrations.AddField(
            model_name="equipment",
            name="subcategory",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="orders.equipmentsubcategory",
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="customer",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="customer",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="subcategory",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="orders.equipmentsubcategory",
            ),
        ),
        migrations.AddField(
            model_name="service",
            name="subcategory",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="subcategory",
                to="orders.equipmentsubcategory",
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="service",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.DO_NOTHING, to="orders.service"
            ),
        ),
    ]
